### ISSUE TITLE
Deployement in validation not working. Missing typeof. 

### ISSUE THREAD

**Issue by victorboissiere** [keymetrics/pm2-io-agent-node#10]
Proxy has to be "string". The only valid of `config.proxy` is 'string'. Could you please fix it as soon as possible ? 

https://github.com/keymetrics/pm2-io-agent-node/blob/master/src/index.js#L28

Best Regards,

**Comment by vmarchaud** [comment]
Fixed on release [1.1.6](https://github.com/keymetrics/pm2-io-agent-node/releases/tag/v1.1.6) via https://github.com/keymetrics/pm2-io-agent-node/commit/e570916fcf9650e663e540bdf33cc27e553985d4
